### ISSUE TITLE
插件无法加载bStats Metrics class has not been relocated correctly!

### ISSUE THREAD

**Issue by HiTech0926** [SlimefunGuguProject/Automation#4]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Automation/issues)，且没有找到相同的问题

### 问题描述

这个额我自己构建的插件（构建站没有），但是出现的问题应该和这个无关
[01:39:28] [Server thread/ERROR]: Error occurred while enabling Automation vUNOFFICIAL (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!

[](https://paste.guizhanss.net/8wBMQ)

### 复现步骤

就……启动之后加载报错啊

### 预期行为

应该正常加载（）

### 服务器日志

https://paste.guizhanss.net/8wBMQ

### 服务端软件

Paper

### Minecraft 版本

1.20.1

### Slimefun版本

![QQ截图20240219014533](https://github.com/SlimefunGuguProject/Automation/assets/112369933/51ef72d6-1316-4386-bcf6-b266be970c05)

### 插件版本

UNOFFICIAL

**Comment by ybw0014** [comment]
插件都没写完

**Comment by HiTech0926** [comment]
> 插件都没写完

az，海曼让我去试试的= =

**Comment by ybw0014** [comment]
你猜为什么这么久都没发构建站
